logging:
  level:
    root: WARN

spring:
  main.banner-mode: "off"

ibm.mq.jms:
  queueManager: queueManagerName
  queueName: queueName
  hostName: hostOrIp
  port: 1414
  channel: channelName
  userName: userName
  password: password

rabbitmq:
  hostname: localhost
  port: 5672
  queueName: queueName

ssl:
  ciphersuite: TLS_RSA_WITH_AES_128_CBC_SHA
  keystore: keystorepath
  keystore.password: keystorePassword
  truststore: truststore
  truststore.password: truststorePassword